# Generated by Django 4.0 on 2021-12-14 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='snippet',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='webApp.snippet'),
        ),
    ]
